version: '3'
services:
  php:
    image: php:7.4-fpm
    volumes:
      - ./server:/var/www/html
    # docker-php-ext-install mysqli

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./server:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - 3306:3306
    volumes:
      - ./docker/test.sql:/test.sql